-- NCPA Sound Ops - Seed Data
-- Equipment catalog (19 items) + Crew roster (14 members)

-- Equipment pre-seed
INSERT OR IGNORE INTO equipment (name, rate) VALUES
  ('D&B M4 MONITORS (FLOOR)', 2500),
  ('SENNHEISER G4 IN-EAR MONITORS', 1500),
  ('SHURE SM58', 300),
  ('SHURE SM57', 300),
  ('SHURE WIRELESS ULXD SM58/HEADSET/LAPEL', 1500),
  ('SHURE SM81', 550),
  ('SHURE BETA 98', 500),
  ('NEUMANN KM184', 750),
  ('SENNHEISER GUN MICS', 600),
  ('FLOOR MICS', 500),
  ('AKG C411', 500),
  ('BSS DI BOX', 250),
  ('2 TRACK RECORDING', 3000),
  ('MULTITRACK RECORDING', 12000),
  ('GOOSENECK PODIUM MICS (SHURE)', 1000),
  ('ALTAIR WIRELESS INTERCOMMS/BELTPACK', 2500),
  ('SENNHEISER E604 (DRUM KIT MICS)', 550),
  ('SHURE BETA 91', 550),
  ('SHURE BETA 52 A', 550);

-- Crew roster (14 members across 4 levels)
INSERT OR IGNORE INTO crew (name, level, can_stage, stage_only_if_urgent, is_outside_crew, venue_capabilities, vertical_capabilities, special_notes) VALUES
  ('Naren', 'Senior', 1, 1, 0, 
   '{"JBT": "Y", "Tata": "Y", "Experimental": "Y", "Little Theatre": "N", "Godrej Dance": "N", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "Y*", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Special: Intl Music FOH'),
  ('Nikhil', 'Senior', 1, 1, 0,
   '{"JBT": "Y*", "Tata": "Y*", "Experimental": "Y*", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "Y*", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Best for JBT/Tata/Exp. Special: Intl Music'),
  ('Coni', 'Senior', 1, 0, 0,
   '{"JBT": "Y", "Tata": "Y", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Cannot FOH Intl Music'),
  ('Sandeep', 'Senior', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Cannot FOH Intl Music'),
  ('Aditya', 'Mid', 1, 0, 0,
   '{"JBT": "Y", "Tata": "Y", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y*", "Intl Music": "N", "Western Music": "Y*", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Special: Indian/Western Music. No Intl'),
  ('Viraj', 'Mid', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "N", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Cannot FOH Intl or Western'),
  ('NS', 'Mid', 1, 0, 0,
   '{"JBT": "Y", "Tata": "Y", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "Y*", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Most flexible. Special: Intl Music'),
  ('Nazar', 'Mid', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "Exp only", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Intl Music FOH ONLY at Experimental'),
  ('Shridhar', 'Mid', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Not JBT/Tata. No Intl Music FOH'),
  ('Omkar', 'Junior', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "N", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Junior. No Intl Music FOH'),
  ('Akshay', 'Junior', 1, 0, 0,
   '{"JBT": "N", "Tata": "N", "Experimental": "Y", "Little Theatre": "Y", "Godrej Dance": "Y", "Others": "Y"}',
   '{"Indian Music": "Y", "Intl Music": "N", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Junior. No Intl Music FOH'),
  ('OC1', 'Hired', 1, 0, 1,
   '{"JBT": "N", "Tata": "N", "Experimental": "N", "Little Theatre": "N", "Godrej Dance": "N", "Others": "N"}',
   '{"Indian Music": "Y", "Intl Music": "Y", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Outside Crew. Stage only.'),
  ('OC2', 'Hired', 1, 0, 1,
   '{"JBT": "N", "Tata": "N", "Experimental": "N", "Little Theatre": "N", "Godrej Dance": "N", "Others": "N"}',
   '{"Indian Music": "Y", "Intl Music": "Y", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Outside Crew. Stage only.'),
  ('OC3', 'Hired', 1, 0, 1,
   '{"JBT": "N", "Tata": "N", "Experimental": "N", "Little Theatre": "N", "Godrej Dance": "N", "Others": "N"}',
   '{"Indian Music": "Y", "Intl Music": "Y", "Western Music": "Y", "Theatre": "Y", "Corporate": "Y", "Library": "Y", "Dance": "Y", "Others": "Y"}',
   'Outside Crew. Stage only.');
